### ISSUE TITLE
Migration error ORA-00904

### ISSUE THREAD

**Issue by AchimFingerhut** [cybertec-postgresql/cybertec_migrator#16] opened 2022-09-13 07:54 UTC
### 📝 Description

When executing migration step "Analyze" Oracle Error 00904 occurs for "column".
![image](https://user-images.githubusercontent.com/19432884/189842483-d993c313-b684-4d04-a957-ec43651d73a3.png)

### 📜 Steps to reproduce

1) Create a new migration
2) ... select source
3) ... select schema
4) ... select dest
5) When doing analsis this error occurs

### 🙁 Actual behavior

Analyzes of source database failed.

### 🙂 Expected behavior

Next migration step should be executed.

### Migrator version

3.10.1-standard (3b23177)

### In which environment are you operating?

- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Other

### What browser are you using

Edge

### Other

Error occurs for every schema i tested.
Even for those with only a few tables.

Using your demo database it works fine.

**Comment by KieranKaelin** [comment] 2022-09-13 08:12
Thanks for creating the ticket!

This looks like a duplicate of #14.
Our CI is lacking here, as we are only testing against Oracle 12.2 and above. Could you verify that you are running on Oracle 11 or below (`SELECT * FROM v$version;`)?

We are discussing the problem internally, and if possible will include the fix in the `v3.11.0` release (end of September).

**Comment by KieranKaelin** [comment] 2022-09-13 11:58
Thank you for the confirmation.
Sadly yes, we currently have no workaround. The problem stems from the differing system catalog between Oracle 11 and 12, to which we will have to adapt our application to.

I will close this issue as it is a duplicate of #14.

**Closed by KieranKaelin** 2022-09-13 11:58 UTC
Labels: bug
