### ISSUE TITLE
Cybertec Migrator 3.10.1 raise error on ORacle 11g whan analyzing Columns

### ISSUE THREAD

**Issue by vicgrin** [cybertec-postgresql/cybertec_migrator#17] opened 2022-09-27 14:05 UTC
### 📝 Description

I've got error on Analyze phase with Oracle 11g and Cybertec Migrator (Standart) 3.10.1 

Error: ORA-00904: "COL"."DEFAULT_ON_NULL": invalid identifier
    at async _0x519a65.query (/app/index.js:5:349249)
    at async _0x519a65.handleQuery (/app/index.js:5:349813)
    at async /app/index.js:5:316719
    at async _0x519a65.handleListener (/app/index.js:5:350755)
    at async _0x519a65.getColumns (/app/index.js:5:314374)
    at async Promise.all (index 1)
    at async _0x519a65.retrieveSystemCatalog (/app/index.js:5:312447)
    at async _0x3bf391.readMetaData (/app/index.js:5:296206)
    at async _0x5199a3.runJob (/app/index.js:5:294303)

Ok

11g
select col.table_name, col.column_name, col.default_on_null from dba_tab_cols col

ORA-00904: "COL"."DEFAULT_ON_NULL": invalid identifier

12c
select col.table_name, col.column_name, col.default_on_null from dba_tab_cols col

### 📜 Steps to reproduce

Make Migration Project
Connect to ORacle 11g
On Phase Analyze - got error

### 🙁 Actual behavior

in Oracle 11g in table dba_tab_cols does not exist column with name default_on_null 

### 🙂 Expected behavior

Complete Analyze without error

### Migrator version

3.10.1

### In which environment are you operating?

- [X] Linux
- [ ] macOS
- [X] Windows
- [ ] Other

### What browser are you using

Ms Edge (Chromium)

### Other

![Screenshot 2022-09-27 170454](https://user-images.githubusercontent.com/91542213/192548619-92767b53-868a-4f5a-9747-7aab44ea8c9d.png)

**Comment by KieranKaelin** [comment] 2022-09-27 19:26
Thanks for creating the ticket!
This looks like a duplicate of #14 and #16.

As of the next release `v3.11.0`, which we will publish tomorrow, we addressed our lacking Oracle 11 test infrastructure and fixed any bugs during the Analyze phase we found.

Closing the issue in order to move traffic to #14.

**Closed by KieranKaelin** 2022-09-27 19:26 UTC
Labels: bug
